<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>Latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CorsairLink.Abstractions\CorsairLink.Abstractions.csproj" />
  </ItemGroup>

</Project>
